config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patients do
    resources :records
    resources :appointments
  end
  root 'patients#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :records
  has_many :appointments

  def self.search(search)
    if search
      where(["name LIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord
  has_many :patients
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_appointment, only: [:show, :edit, :update, :destroy]

  def index
    @appointments = Appointment.all.order("created_at DESC")
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to @appointment
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment
    else
      render 'edit'
    end
  end

  def destroy
    @appointment.destroy
    redirect_to root_path
  end

  private
    def appointment_params
      params.require(:appointment).permit(:date, :time, :doctor)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :find_patient, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      @patients = Patient.where(:user_id => current_user.id).order("created_at DESC")
      @patients = Patient.search(params[:search])
    end
  end

  def show
  end

  def new
    @patient = current_user.patients.build
  end

  def create
    @patient = current_user.patients.build(patient_params)
    if @patient.save
      flash[:notice] = "Patient was successfully created."
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to patient_path(@patient)
    else
      render 'edit'
    end
  end

  def destroy
    @patient.destroy
    redirect_to root_path
  end

  private
    def patient_params
      params.require(:patient).permit(:name, :surname, :address, :date_of_birth, :phone_no, :medical_card, :medical_insurance)
    end

    def find_patient
      @patient = Patient.find(params[:id])
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :find_record, only: [:show, :edit, :update, :destroy]

  def index
    @records = Record.all.order("created_at DESC")
  end

  def show
  end

  def new
    @patient = Patient.find(params[:patient_id])
    @record = Record.new
  end

  def create
    @patient = Patient.find(params[:patient_id])
    @record = @patient.records.create(record_params)

    if @record.save
      redirect_to patient_path(@patient)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @record.destroy
    redirect_to patient_path
  end

  private
    def record_params
      params.permit(:observation, :previous_condition, :blood_test, :sick_note)
    end

    def find_record
      @record = Record.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for @patient.appointments do |f| %>
  <%= f.input :date, label: "Date" %>
  <%= f.input :time, label: "Time" %>
  <%= f.input :doctor, label: "Doctor" %>
  <%= f.button :submit %>
<% end %>

app/views/appointments/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="surrounding-box">
    <h1>New Appointment Details</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/layouts/_landing_page.html.erb
<main role="main" class="container">
  <div class="jumbotron">
    <h1><%= image_tag("SHCS.png") %> Smart Health Care System</h1>
    <p>A Doctor to Patient Solution</p>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
    <%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartHealthCareSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <div class="container">
        <div class="navbar-header">
          <% if current_user.present? %>
            <%= link_to "Patients", root_path, class: "navbar-brand" %>
          <% else %>
            <%= link_to "Smart Health Care System", root_path, class: "navbar-brand" %>
          <% end %>
        </div>
        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if current_user.present? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <%= link_to "Add New Patient", new_patient_path, class: "btn btn-success navbar-text navbar-link navbar-right" %>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>


  </body>
</html>

app/views/patients/_form.html.erb
<%= simple_form_for @patient do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :surname, label: "Surname" %>
  <%= f.input :address, label: "Address" %>
  <%= f.input :date_of_birth, label: "Date of Birth" %>
  <%= f.input :phone_no, label: "Phone No.:" %>
  <%= f.input :medical_card, label: "Medical Card" %>
  <%= f.input :medical_insurance, label: "Medical Insurance" %>
  <%= f.button :submit %>
<% end %>

app/views/patients/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="surrounding-box">
    <h1>Edit Patient Details</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/patients/index.html.erb
<% if user_signed_in? %>
  <div class="col-md-6 col-md-offset-3">
    <div class="surrounding-box">
      <div class="search">
        <%= form_tag patients_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Patients", class: 'form-control' %><br>
          <%= submit_tag 'Search', class: "btn btn-primary pull-right" %>
        <% end %>
      </div>
      <h2>Your Most Recent Patients</h2>
        <% @patients.each do |patient| %>
          <div class="patient-box">
            <div class="patient-name">
                <h3><%= patient.name %> <%= patient.surname %></h3>
            </div>
            <div class="patient-details-btn">
                <%= link_to "Patient Details", patient, class: "btn btn-primary pull-right" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
<% else %>
  <%= render 'layouts/landing_page' %>
<% end %>

app/views/patients/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="surrounding-box">
    <h1>New Patient Details</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/patients/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="col-md-6">
    <div class="surrounding-box">
      <h2><strong><%= @patient.name %> <%= @patient.surname %></strong></h2>
      <h4><strong>Address:</strong></h4>
      <p><%= @patient.address %></p>
      <h4><strong>Date of Birth:</strong></h4>
      <p><%= @patient.date_of_birth %></p>
      <h4><strong>Phone Number:</strong></h4>
      <p><%= @patient.phone_no %></p>
      <h4><strong>Medical Card:</strong></h4>
      <p><%= @patient.medical_card %></p>
      <h4><strong>Medical Insurance:</strong></h4>
      <p><%= @patient.medical_insurance %></p>
      <%= link_to "Back", root_path, class: "btn btn-primary" %>
      <%= link_to "Edit", edit_patient_path(@patient), class: "btn btn-primary" %>
      <%= link_to "Delete", patient_path(@patient), class: "btn btn-primary", method: :delete, data: { confirm: "Are You Sure?" } %>
      <%= link_to "Add New Appointment", new_patient_path, class: "btn btn-primary pull-right" %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="surrounding-box">
      <h2>Records</h2>
      <% @patient.records[0,4].reverse_each do |record| %>
        <div class="record-box">
          <div class="record-title">
            <h5><strong>Created At: <%= record.created_at %></strong></h5>
          </div>
          <div class="show-record-btn">
            <%= link_to "Show Record", patient_record_path(@patient), class: "btn btn-primary pull-right" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="add-record-btn">
      <%= link_to "Add Record", new_patient_record_path(@patient), class: "btn btn-primary btn-success" %>
    </div>
  </div>
</div>

app/views/records/_form.html.erb
<%= simple_form_for [@patient, @patient.records.build] do |f| %>
  <%= f.input :observation, label: "Observation" %>
  <%= f.input :previous_condition, label: "Previous Conditions" %>
  <%= f.input :blood_test, label: "Blood Test" %>
  <%= f.input :sick_note, label: "Sick Note" %>
  <%= f.button :submit %>
<% end %>

app/views/records/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="surrounding-box">
    <h1>Edit Record Details</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/records/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="surrounding-box">
    <h1>New Record Details</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/records/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="surrounding-box">
    <h3>Observations:</h3><br>
    <p><%= @record.observation %></p><br>
    <h3>Previous Conditions:</h3><br>
    <p><%= @record.previous_condition %></p><br>
    <h3>Blood Test: </h3>
    <p><%= @record.blood_test %></p><br>
    <h3>Sick Note: </h3>
    <p><%= @record.sick_note %></p>
    <%= link_to "Back", patient_path, class: "btn btn-primary" %>
    <%= link_to "Delete", patient_path(@record), class: "btn btn-primary", method: :delete, data: { confirm: "Are You Sure?" } %>
  </div>
</div>